### ISSUE TITLE
Adding count to charts labels

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#433]
For printing, it would be better to have the count displaying on the legends labels, as users can't see the tips on the charts

I found where to change the legend labels, but I'm not sure how to display the counts only on the print page ?

![Capture d’écran 2020-05-07 à 11 59 41](https://user-images.githubusercontent.com/2345926/81281533-40fcff00-905a-11ea-805d-4d969725b087.png)

**Comment by SamMousa** [comment]
If the counts are HTML you could add a span with a `print-only` utility class.
Then have that class be invisible on media that is not print:
```css
@media not print {
    .print-only {
        display: none
    }
}
```
